import { DetailedPaper } from './src/types';

// Detailed paper information for LLM context
// This data is used to provide rich context to the AI assistant but is not displayed on the website
export const DETAILED_PAPERS: DetailedPaper[] = [
  {
    id: "p1", // Should match the ID from constants.ts PAPERS array
    title: "BoTTA: Benchmarking on-device Test Time Adaptation",
    authors: ["Michal Danilowski", "Soumyajit Chatterjee", "Abhirup Ghosh"],
    venue: "accepted in SenSys",
    year: 2026,
    abstract: "BoTTA introduces a benchmark to evaluate test-time adaptation (TTA) methods under realistic on-device constraints (limited samples, limited categories, diverse shifts) and reports system-level metrics on real devices to guide practical TTA for mobile and edge deployments.",
    fullAbstract: "", // You can add the full abstract here
    link: "https://arxiv.org/abs/2504.10149",
    pdfLink: "", // Direct PDF link if different from main link
    tags: ["Test-Time Adaptation", "On-device", "Benchmark"],
    keywords: [], // Additional keywords for LLM context
    methodology: "", // Description of methodology used
    keyFindings: [], // Key findings and contributions
    relatedWork: "", // Related work context
    futureWork: "", // Future work and limitations
    citations: 0, // Citation count if available
    doi: "", // DOI if available
    bibtex: "" // BibTeX citation
  },
  {
    id: "p2",
    title: "E-BATS: Efficient Backpropagation-Free Test-Time Adaptation for Speech Foundation Models",
    authors: ["Jiaheng Dong", "Hong Jia", "Soumyajit Chatterjee", "Abhirup Ghosh", "James Bailey", "Ting Dang"],
    venue: "accepted in NeurIPS",
    year: 2025,
    abstract: "E-BATS introduces the first efficient backpropagation-free TTA framework designed explicitly for speech foundation models, achieving 4.1%–13.5% accuracy gains over backpropagation-free baselines and 2.0×–6.4× GPU memory savings through lightweight prompt adaptation, multi-scale loss, and test-time exponential moving average mechanism.",
    fullAbstract: "Speech Foundation Models encounter significant performance degradation when deployed in real-world scenarios involving acoustic domain shifts, such as background noise and speaker accents. Test-time adaptation (TTA) has recently emerged as a viable strategy to address such domain shifts at inference time without requiring access to source data or labels. However, existing TTA approaches, particularly those relying on backpropagation, are memory-intensive, limiting their applicability in speech tasks and resource-constrained settings. Although backpropagation-free methods offer improved efficiency, existing ones exhibit poor accuracy. This is because they are predominantly developed for vision tasks, which fundamentally differ from speech task formulations, noise characteristics, and model architecture, posing unique transferability challenges. In this paper, we introduce E-BATS, the first Efficient BAckpropagation-free TTA framework designed explicitly for speech foundation models. E-BATS achieves a balance between adaptation effectiveness and memory efficiency through three key components: (i) lightweight prompt adaptation for a forward-pass-based feature alignment, (ii) a multi-scale loss to capture both global (utterance-level) and local distribution shifts (token-level) and (iii) a test-time exponential moving average mechanism for stable adaptation across utterances. Experiments conducted on four noisy speech datasets spanning sixteen acoustic conditions demonstrate consistent improvements, with 4.1%–13.5% accuracy gains over backpropagation-free baselines and 2.0×–6.4× GPU memory savings compared to backpropagation-based methods. By enabling scalable and robust adaptation under acoustic variability, this work paves the way for developing more efficient adaptation approaches for practical speech processing systems in real-world environments.",
    link: "https://arxiv.org/abs/2506.07078",
    pdfLink: "",
    tags: ["Speech", "Test-Time Adaptation", "Efficient TTA"],
    keywords: ["speech foundation models", "test-time adaptation", "backpropagation-free", "acoustic domain shifts", "prompt adaptation", "multi-scale loss", "exponential moving average", "memory efficiency", "speech processing"],
    methodology: "E-BATS uses three key components: (1) lightweight prompt adaptation for forward-pass-based feature alignment, (2) a multi-scale loss to capture both global (utterance-level) and local distribution shifts (token-level), and (3) a test-time exponential moving average mechanism for stable adaptation across utterances. Evaluated on four noisy speech datasets spanning sixteen acoustic conditions including background noise and speaker accents.",
    keyFindings: [
      "First efficient backpropagation-free TTA framework designed explicitly for speech foundation models",
      "4.1%–13.5% accuracy gains over backpropagation-free baselines",
      "2.0×–6.4× GPU memory savings compared to backpropagation-based methods",
      "Consistent improvements across four noisy speech datasets spanning sixteen acoustic conditions",
      "Addresses unique transferability challenges from vision to speech tasks",
      "Enables scalable and robust adaptation under acoustic variability"
    ],
    relatedWork: "Addresses limitations of existing TTA approaches that are memory-intensive when using backpropagation, or exhibit poor accuracy when backpropagation-free. Most existing backpropagation-free methods are developed for vision tasks and don't transfer well to speech due to fundamental differences in task formulations, noise characteristics, and model architecture.",
    futureWork: "Paves the way for developing more efficient adaptation approaches for practical speech processing systems in real-world environments with acoustic variability.",
    citations: 0,
    doi: "",
    bibtex: ""
  },
  {
    id: "p7",
    title: "NEO: No-Optimization Test-Time Adaptation through Latent Re-Centering",
    authors: ["Alexander Murphy", "Michal Danilowski", "Soumyajit Chatterjee", "Abhirup Ghosh"],
    venue: "arXiv preprint",
    year: 2025,
    abstract: "NEO is a hyperparameter-free fully TTA method that significantly improves alignment between source and distribution-shifted samples by re-centering target data embeddings at the origin, achieving state-of-the-art results with minimal compute overhead.",
    fullAbstract: "Test-Time Adaptation (TTA) methods are often computationally expensive, require a large amount of data for effective adaptation, or are brittle to hyperparameters. Based on a theoretical foundation of the geometry of the latent space, we are able to significantly improve the alignment between source and distribution-shifted samples by re-centering target data embeddings at the origin. This insight motivates NEO -- a hyperparameter-free fully TTA method, that adds no significant compute compared to vanilla inference. NEO is able to improve the classification accuracy of ViT-Base on ImageNet-C from 55.6% to 59.2% after adapting on just one batch of 64 samples. When adapting on 512 samples NEO beats all 7 TTA methods we compare against on ImageNet-C, ImageNet-R and ImageNet-S and beats 6/7 on CIFAR-10-C, while using the least amount of compute. NEO performs well on model calibration metrics and additionally is able to adapt from 1 class to improve accuracy on 999 other classes in ImageNet-C. On Raspberry Pi and Jetson Orin Nano devices, NEO reduces inference time by 63% and memory usage by 9% compared to baselines.",
    link: "https://arxiv.org/abs/2510.05635",
    pdfLink: "",
    tags: ["Test-Time Adaptation", "Computer Vision", "Efficient TTA"],
    keywords: ["test-time adaptation", "domain shift", "latent space geometry", "re-centering", "hyperparameter-free", "edge devices", "ViT", "ImageNet"],
    methodology: "NEO is based on theoretical insights about the geometry of latent spaces. The key insight is that re-centering target data embeddings at the origin significantly improves alignment between source and distribution-shifted samples. The method is hyperparameter-free and adds minimal computational overhead compared to vanilla inference. Evaluated on ViT architectures with ImageNet-C, ImageNet-R, ImageNet-S, and CIFAR-10-C datasets, as well as edge devices (Raspberry Pi and Jetson Orin Nano).",
    keyFindings: [
      "Improves ViT-Base classification accuracy on ImageNet-C from 55.6% to 59.2% with just one batch of 64 samples",
      "Outperforms 7 TTA methods on ImageNet-C, ImageNet-R, and ImageNet-S when adapting on 512 samples",
      "Beats 6/7 methods on CIFAR-10-C while using the least amount of compute",
      "Demonstrates good model calibration metrics",
      "Can adapt from 1 class to improve accuracy on 999 other classes in ImageNet-C",
      "Reduces inference time by 63% and memory usage by 9% on edge devices (Raspberry Pi and Jetson Orin Nano)"
    ],
    relatedWork: "Addresses limitations of existing TTA methods that are computationally expensive, require large amounts of data, or are brittle to hyperparameters. Builds on theoretical understanding of latent space geometry for domain adaptation.",
    futureWork: "The approach opens up possibilities for efficient TTA on resource-constrained edge devices and could be extended to other architectures beyond ViTs.",
    citations: 0,
    doi: "",
    bibtex: `@article{murphy2025neo,
  title={NEO: No-Optimization Test-Time Adaptation through Latent Re-Centering},
  author={Murphy, Alexander and Danilowski, Michal and Chatterjee, Soumyajit and Ghosh, Abhirup},
  journal={arXiv preprint arXiv:2510.05635},
  year={2025}
}`
  },
  {
    id: "p3",
    title: "Uncertainty-Aware Personalized Federated Learning for Realistic Healthcare Applications",
    authors: ["Yuwei Zhang", "Tong Xia", "Abhirup Ghosh", "Cecilia Mascolo"],
    venue: "Machine Learning for Health (ML4H)@NeurIPS",
    year: 2025,
    abstract: "Healthcare applications require accurate and uncertainty-aware machine learning models, providing confidence rather than only blackbox predictions. However, training such deep learning models with insufficient data at individual sites (e.g., hospitals) poses a challenge. Federated learning (FL) mitigates this by allowing data holders to collaboratively train models without sharing sensitive health data. Yet, we identify two major realistic challenges when building uncertainty estimates in FL, severe data heterogeneity and high computational overhead. This paper proposes FedEE, an uncertainty-aware and efficient personalized FL framework for realistic healthcare applications. FedEE achieves an efficient way of ensembling by incorporating lightweight early exit blocks into a single backbone model. These blocks are personalized for each client to tackle data heterogeneity. Experiments with four FL strategies and three datasets demonstrate that FedEE achieves up to a 15% improvement in uncertainty estimation from vanilla softmax entropy and is competitive with expensive baselines, showcasing in the order of 5× improved efficiency with a 5-member ensemble.",
    fullAbstract: "Healthcare applications require accurate and uncertainty-aware machine learning models, providing confidence rather than only blackbox predictions. However, training such deep learning models with insufficient data at individual sites (e.g., hospitals) poses a challenge. Federated learning (FL) mitigates this by allowing data holders to collaboratively train models without sharing sensitive health data. Yet, we identify two major realistic challenges when building uncertainty estimates in FL, severe data heterogeneity and high computational overhead. This paper proposes FedEE, an uncertainty-aware and efficient personalized FL framework for realistic healthcare applications. FedEE achieves an efficient way of ensembling by incorporating lightweight early exit blocks into a single backbone model. These blocks are personalized for each client to tackle data heterogeneity. Experiments with four FL strategies and three datasets demonstrate that FedEE achieves up to a 15% improvement in uncertainty estimation from vanilla softmax entropy and is competitive with expensive baselines, showcasing in the order of 5× improved efficiency with a 5-member ensemble.",
    link: "https://www.semanticscholar.org/paper/dcd30d03770924b583517eec1509873d47949fb2",
    pdfLink: "",
    tags: ["Federated Learning", "Healthcare", "Uncertainty", "Personalization"],
    keywords: ["federated learning", "uncertainty estimation", "healthcare", "personalization", "early exit", "ensemble methods", "data heterogeneity", "privacy-preserving", "computational efficiency"],
    methodology: "FedEE incorporates lightweight early exit blocks into a single backbone model, with blocks personalized for each client to tackle data heterogeneity. The approach uses efficient ensembling methods and was evaluated with four FL strategies across three datasets, comparing against vanilla softmax entropy and expensive baseline methods.",
    keyFindings: [
      "Identifies two major challenges in FL uncertainty estimation: severe data heterogeneity and high computational overhead",
      "FedEE achieves up to 15% improvement in uncertainty estimation compared to vanilla softmax entropy",
      "Demonstrates 5× improved efficiency with a 5-member ensemble compared to expensive baselines",
      "Shows competitive performance across four FL strategies and three datasets",
      "Provides personalized early exit blocks to address client-specific data heterogeneity"
    ],
    relatedWork: "Addresses the gap in uncertainty-aware federated learning for healthcare, where traditional FL approaches don't adequately handle uncertainty estimation under severe data heterogeneity and computational constraints.",
    futureWork: "The efficient uncertainty-aware FL framework opens possibilities for broader healthcare applications where both accuracy and confidence estimates are critical for clinical decision-making.",
    citations: 0,
    doi: "",
    bibtex: ""
  },
  {
    id: "p6",
    title: "FLea: Addressing Data Scarcity and Label Skew in Federated Learning via Privacy-preserving Feature Augmentation",
    authors: ["Tong Xia", "Abhirup Ghosh", "Xinchi Qiu", "Cecilia Mascolo"],
    venue: "KDD",
    year: 2024,
    abstract: "Federated Learning (FL) enables model development by leveraging data distributed across numerous edge devices without transferring local data to a central server. However, existing FL methods still face challenges when dealing with scarce and label-skewed data across devices, resulting in local model overfitting and drift, consequently hindering the performance of the global model. In response to these challenges, we propose a pioneering framework called FLea, incorporating the following key components: i) A global feature buffer that stores activation-target pairs shared from multiple clients to support local training. This design mitigates local model drift caused by the absence of certain classes; ii) A feature augmentation approach based on local and global activation mix-ups for local training. This strategy enlarges the training samples, thereby reducing the risk of local overfitting; iii) An obfuscation method to minimize the correlation between intermediate activations and the source data, enhancing the privacy of shared features. To verify the superiority of FLea, we conduct extensive experiments using a wide range of data modalities, simulating different levels of local data scarcity and label skew. The results demonstrate that FLea consistently outperforms state-of-the-art FL counterparts (among 13 of the experimented 18 settings, the improvement is over 5%) while concurrently mitigating the privacy vulnerabilities associated with shared features. Code is available at https://github.com/XTxiatong/FLea.git.",
    fullAbstract: "Federated Learning (FL) enables model development by leveraging data distributed across numerous edge devices without transferring local data to a central server. However, existing FL methods still face challenges when dealing with scarce and label-skewed data across devices, resulting in local model overfitting and drift, consequently hindering the performance of the global model. In response to these challenges, we propose a pioneering framework called FLea, incorporating the following key components: i) A global feature buffer that stores activation-target pairs shared from multiple clients to support local training. This design mitigates local model drift caused by the absence of certain classes; ii) A feature augmentation approach based on local and global activation mix-ups for local training. This strategy enlarges the training samples, thereby reducing the risk of local overfitting; iii) An obfuscation method to minimize the correlation between intermediate activations and the source data, enhancing the privacy of shared features. To verify the superiority of FLea, we conduct extensive experiments using a wide range of data modalities, simulating different levels of local data scarcity and label skew. The results demonstrate that FLea consistently outperforms state-of-the-art FL counterparts (among 13 of the experimented 18 settings, the improvement is over 5%) while concurrently mitigating the privacy vulnerabilities associated with shared features. Code is available at https://github.com/XTxiatong/FLea.git.",
    link: "https://dl.acm.org/doi/10.1145/3637528.3671899",
    pdfLink: "",
    tags: ["Federated Learning", "Data Augmentation", "Privacy"],
    keywords: ["federated learning", "data scarcity", "label skew", "feature augmentation", "activation mix-up", "global feature buffer", "privacy preservation", "obfuscation", "local model drift", "edge devices"],
    methodology: "FLea incorporates three key components: (1) A global feature buffer that stores activation-target pairs shared from multiple clients to support local training and mitigate local model drift caused by missing classes, (2) A feature augmentation approach based on local and global activation mix-ups to enlarge training samples and reduce local overfitting, and (3) An obfuscation method to minimize correlation between intermediate activations and source data for enhanced privacy. Evaluated across wide range of data modalities with different levels of local data scarcity and label skew.",
    keyFindings: [
      "Addresses key challenges in FL: scarce and label-skewed data leading to local model overfitting and drift",
      "Consistently outperforms state-of-the-art FL counterparts across multiple settings",
      "Achieves over 5% improvement in 13 out of 18 experimental settings",
      "Successfully mitigates privacy vulnerabilities associated with shared features",
      "Demonstrates effectiveness across wide range of data modalities",
      "Provides open-source implementation for reproducibility"
    ],
    relatedWork: "Addresses limitations of existing FL methods that struggle with scarce and label-skewed data across devices, which leads to local model overfitting and drift that hinders global model performance.",
    futureWork: "The framework opens possibilities for more robust federated learning in realistic scenarios with non-IID data distributions and privacy constraints.",
    citations: 0,
    doi: "",
    bibtex: ""
  },
  {
    id: "p4",
    title: "Modeling with Homophily Driven Heterogeneous Data in Gossip Learning",
    authors: ["Abhirup Ghosh", "Cecilia Mascolo"],
    venue: "IJCAI",
    year: 2023,
    abstract: "Proposes a neighbor-weighting strategy for Gossip Learning to accelerate convergence when devices have homophily-driven heterogeneous data; includes efficient and fair augmentations and evaluation on real and synthetic datasets.",
    fullAbstract: "Training deep learning models on data distributed and local to edge devices such as mobile phones is a prominent recent research direction. In a Gossip Learning (GL) system, each participating device maintains a model trained on its local data and iteratively aggregates it with the models from its neighbours in a communication network. While the fully distributed operation in GL comes with natural advantages over the centralized orchestration in Federated Learning (FL), its convergence becomes particularly slow when the data distribution is heterogeneous and aligns with the clustered structure of the communication network. These characteristics are pervasive across practical applications as people with similar interests (thus producing similar data) tend to create communities. This paper proposes a data-driven neighbor weighting strategy for aggregating the models: this enables faster diffusion of knowledge across the communities in the network and leads to quicker convergence. We augment the method to make it computationally efficient and fair: the devices quickly converge to the same model. We evaluate our model on real and synthetic datasets that we generate using a novel generative model for communication networks with heterogeneous data. Our exhaustive empirical evaluation verifies that our proposed method attains a faster convergence rate than the baselines. For example, the median test accuracy for a decentralized bird image classifier application reaches 81% with our proposed method within 80 rounds, whereas the baseline only reaches 46%.",
    link: "https://www.ijcai.org/proceedings/2023/0416.pdf",
    pdfLink: "",
    tags: ["Gossip Learning", "Heterogeneous Data", "Federated Learning"],
    keywords: ["gossip learning", "federated learning", "decentralized machine learning", "heterogeneous data", "homophily", "edge computing", "model aggregation", "neighbor weighting"],
    methodology: "Proposed a data-driven neighbor weighting strategy for model aggregation in Gossip Learning systems. Developed computationally efficient and fair augmentations to ensure devices converge to the same model. Created a novel generative model for communication networks with heterogeneous data. Evaluated on both real and synthetic datasets with comprehensive empirical analysis.",
    keyFindings: [
      "Data-driven neighbor weighting significantly accelerates convergence in heterogeneous Gossip Learning environments",
      "Method enables faster diffusion of knowledge across network communities with clustered data distributions",
      "Proposed approach achieves 81% median test accuracy within 80 rounds vs. 46% for baseline methods",
      "Novel generative model successfully captures communication network characteristics with heterogeneous data",
      "Computationally efficient implementation maintains fairness while improving convergence speed"
    ],
    relatedWork: "Builds upon traditional Gossip Learning and Federated Learning paradigms by addressing the specific challenge of heterogeneous data distribution aligned with network clustering. Related to distributed machine learning, edge computing, and homophily-driven networks.",
    futureWork: "Extension to more complex network topologies, integration with privacy-preserving techniques, and application to larger-scale real-world deployments with diverse data modalities.",
    citations: 0,
    doi: "",
    bibtex: ""
  },
  {
    id: "p5",
    title: "Machine learning detects altered spatial navigation features in outdoor behaviour of Alzheimer's disease patients",
    authors: ["Abhirup Ghosh", "Vaisakh Puthusseryppady", "Dennis Chan", "Cecilia Mascolo", "Michael Hornberger"],
    venue: "Scientific Reports",
    year: 2022,
    abstract: "Using GPS tracking and machine learning, this study identifies spatiotemporal outdoor navigation features that discriminate Alzheimer's disease patients from controls, demonstrating potential wearable-based digital biomarkers.",
    fullAbstract: "",
    link: "https://doi.org/10.1038/s41598-022-06899-w",
    pdfLink: "",
    tags: ["Digital Biomarkers", "Alzheimer's", "Wearables", "Mobility"],
    keywords: [],
    methodology: "",
    keyFindings: [],
    relatedWork: "",
    futureWork: "",
    citations: 0,
    doi: "",
    bibtex: ""
  },
  {
    id: "p8",
    title: "Human-centred artificial intelligence for mobile health sensing: challenges and opportunities",
    authors: ["Ting Dang", "Dimitris Spathis", "Abhirup Ghosh", "Cecilia Mascolo"],
    venue: "Royal Society Open Science",
    year: 2023,
    abstract: "Advances in wearable sensing and mobile computing have enabled the collection of health and well-being data outside of traditional laboratory and hospital settings, paving the way for a new era of mobile health. Meanwhile, artificial intelligence (AI) has made significant strides in various domains, demonstrating its potential to revolutionize healthcare. Devices can now diagnose diseases, predict heart irregularities and unlock the full potential of human cognition. However, the application of machine learning (ML) to mobile health sensing poses unique challenges due to noisy sensor measurements, high-dimensional data, sparse and irregular time series, heterogeneity in data, privacy concerns and resource constraints. Despite the recognition of the value of mobile sensing, leveraging these datasets has lagged behind other areas of ML. Furthermore, obtaining quality annotations and ground truth for such data is often expensive or impractical. While recent large-scale longitudinal studies have shown promise in leveraging wearable sensor data for health monitoring and prediction, they also introduce new challenges for data modelling. This paper explores the challenges and opportunities of human-centred AI for mobile health, focusing on key sensing modalities such as audio, location and activity tracking. We discuss the limitations of current approaches and propose potential solutions.",
    fullAbstract: "Advances in wearable sensing and mobile computing have enabled the collection of health and well-being data outside of traditional laboratory and hospital settings, paving the way for a new era of mobile health. Meanwhile, artificial intelligence (AI) has made significant strides in various domains, demonstrating its potential to revolutionize healthcare. Devices can now diagnose diseases, predict heart irregularities and unlock the full potential of human cognition. However, the application of machine learning (ML) to mobile health sensing poses unique challenges due to noisy sensor measurements, high-dimensional data, sparse and irregular time series, heterogeneity in data, privacy concerns and resource constraints. Despite the recognition of the value of mobile sensing, leveraging these datasets has lagged behind other areas of ML. Furthermore, obtaining quality annotations and ground truth for such data is often expensive or impractical. While recent large-scale longitudinal studies have shown promise in leveraging wearable sensor data for health monitoring and prediction, they also introduce new challenges for data modelling. This paper explores the challenges and opportunities of human-centred AI for mobile health, focusing on key sensing modalities such as audio, location and activity tracking. We discuss the limitations of current approaches and propose potential solutions.",
    link: "https://royalsocietypublishing.org/doi/10.1098/rsos.230806",
    pdfLink: "",
    tags: ["Mobile Health", "Wearable Sensing", "Human-Centred AI", "Survey"],
    keywords: ["mobile health", "wearable sensing", "human-centred AI", "mHealth", "sensor measurements", "longitudinal studies", "audio sensing", "location tracking", "activity tracking", "digital biomarkers", "healthcare AI", "privacy", "data heterogeneity"],
    methodology: "This paper provides a comprehensive survey of human-centred AI for mobile health sensing, focusing on key sensing modalities including audio, location, and activity tracking. The authors analyze challenges in mobile health ML including noisy sensor measurements, high-dimensional data, sparse and irregular time series, data heterogeneity, privacy concerns, and resource constraints. The work reviews current approaches and proposes potential solutions for leveraging wearable sensor data effectively.",
    keyFindings: [
      "Identifies unique challenges in mobile health ML: noisy sensors, high-dimensional data, sparse time series, heterogeneity, privacy, and resource constraints",
      "Mobile sensing dataset utilization has lagged behind other ML areas despite recognized value",
      "Quality annotations and ground truth are expensive or impractical to obtain for mobile health data",
      "Large-scale longitudinal studies show promise but introduce new data modeling challenges",
      "Current approaches have significant limitations in handling mobile health sensing data",
      "Proposes potential solutions for key sensing modalities: audio, location, and activity tracking"
    ],
    relatedWork: "Builds on advances in wearable sensing and mobile computing that enable health data collection outside traditional settings. Relates to broader AI advances in healthcare while addressing specific challenges of mobile health sensing that differ from laboratory-based medical AI applications.",
    futureWork: "The paper identifies opportunities for developing more robust human-centred AI approaches for mobile health that can handle the unique challenges of real-world sensing data while maintaining privacy and operating under resource constraints.",
    citations: 0,
    doi: "10.1098/rsos.230806",
    bibtex: `@article{dang2023human,
  title={Human-centred artificial intelligence for mobile health sensing: challenges and opportunities},
  author={Dang, Ting and Spathis, Dimitris and Ghosh, Abhirup and Mascolo, Cecilia},
  journal={Royal society open science},
  volume={10},
  number={11},
  pages={230806},
  year={2023},
  publisher={The Royal Society}
}`
  },
  {
    id: "p9",
    title: "Cross-device federated learning for mobile health diagnostics: A first study on COVID-19 detection",
    authors: ["Tong Xia", "Jing Han", "Abhirup Ghosh", "Cecilia Mascolo"],
    venue: "ICASSP",
    year: 2023,
    abstract: "FedLoss introduces a novel cross-device federated learning framework for health diagnostics that averages models based on predictive loss rather than sample count, achieving 79% AUC-ROC for COVID-19 detection.",
    fullAbstract: "Federated learning (FL) aided health diagnostic models can incorporate data from a large number of personal edge devices (e.g., mobile phones) while keeping the data local to the originating devices, largely ensuring privacy. However, such a cross-device FL approach for health diagnostics still imposes many challenges due to both local data imbalance (as extreme as local data consists of a single disease class) and global data imbalance (the disease prevalence is generally low in a population). Since the federated server has no access to data distribution information, it is not trivial to solve the imbalance issue towards an unbiased model. In this paper, we propose FedLoss, a novel cross-device FL framework for health diagnostics. Here the federated server averages the models trained on edge devices according to the predictive loss on the local data, rather than using only the number of samples as weights. As the predictive loss better quantifies the data distribution at a device, FedLoss alleviates the impact of data imbalance. Through a real-world dataset on respiratory sound and symptom-based COVID-19 detection task, we validate the superiority of FedLoss. It achieves competitive COVID-19 detection performance compared to a centralised model with an AUC-ROC of 79%. It also outperforms the state-of-the-art FL baselines in sensitivity and convergence speed. Our work not only demonstrates the promise of federated COVID-19 detection but also paves the way to a plethora of mobile health model development in a privacy-preserving fashion.",
    link: "https://ieeexplore.ieee.org/document/10096516",
    pdfLink: "",
    tags: ["Federated Learning", "Mobile Health", "COVID-19"],
    keywords: ["federated learning", "mobile health", "COVID-19 detection", "data imbalance", "cross-device", "privacy-preserving", "respiratory sound", "health diagnostics"],
    methodology: "Proposed FedLoss framework that averages models based on predictive loss rather than just sample count. Used real-world respiratory sound and symptom data for COVID-19 detection. Compared against state-of-the-art federated learning baselines and centralized models. Evaluated performance using AUC-ROC, sensitivity, and convergence speed metrics.",
    keyFindings: [
      "FedLoss achieves 79% AUC-ROC for COVID-19 detection, competitive with centralized models",
      "Outperforms state-of-the-art federated learning baselines in sensitivity and convergence speed",
      "Predictive loss-based model averaging better handles data imbalance than sample count weighting",
      "Successfully addresses both local and global data imbalance challenges in health diagnostics",
      "Demonstrates feasibility of privacy-preserving federated COVID-19 detection using mobile devices"
    ],
    relatedWork: "Builds on federated learning frameworks and mobile health diagnostics. Addresses specific challenges of cross-device FL in healthcare settings, particularly data imbalance issues that are prevalent in health applications where disease prevalence is typically low.",
    futureWork: "Extension to other health diagnostic tasks, integration with more diverse mobile health sensors, and exploration of additional techniques to handle data heterogeneity in federated health applications.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{xia2023cross,
  title={Cross-device federated learning for mobile health diagnostics: A first study on COVID-19 detection},
  author={Xia, Tong and Han, Jing and Ghosh, Abhirup and Mascolo, Cecilia},
  booktitle={ICASSP 2023-2023 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)},
  pages={1--5},
  year={2023},
  organization={IEEE}
}`
  },
  {
    id: "p10",
    title: "Investigating domain-agnostic performance in activity recognition using accelerometer data",
    authors: ["Apinan Hasthanasombat", "Abhirup Ghosh", "Dimitris Spathis", "Cecilia Mascolo"],
    venue: "UbiComp/ISWC Adjunct",
    year: 2022,
    abstract: "Presents domain-agnostic human activity recognition models that generalize to unseen test domains without requiring target domain data, using a leave-datasets-out evaluation regime and showing simple models can outperform deep learning approaches.",
    fullAbstract: "Human activity recognition (HAR) models suffer significant performance degradation when faced with data heterogeneity (device, users, environments) at test time. Current approaches to this problem using domain adaptation or transfer learning attempt to improve performance in one specific target domain, often using data from said domain. Requiring access to data from the target domain is limiting and cannot be generally assumed. In addition, there is often no single target domain, but rather multiple ones arising from different sources of data heterogeneity. One way to achieve good performance in this setting would be to gather data from all potential domains the model may encounter at deployment - this is generally infeasible. This work presents the case for training models which are domain-agnostic, i.e., that generalise to unseen test domains. This requires a new way to evaluate models; we discuss a regime called leave-datasets-out, and present a starting benchmark for HAR using binary classification. Two state-of-the-art deep models in the literature are tested; they significantly under-perform in unseen domains when compared to their performance on seen domains. It is shown that under this new evaluation regime, a simple model with an appropriate inductive bias performs at least as well as two current deep models on the benchmark, with a p-value of 5.75x10−4 and 0.13 when testing for a difference in mean accuracy, whilst being at least 10 times faster to train. Additionally, we provide evidence that domain diversity under certain conditions improves performance on both seen and unseen domains. We hope this work provides useful insights to further develop HAR models suitable for real world deployment.",
    link: "https://dl.acm.org/doi/10.1145/3544793.3560381",
    pdfLink: "",
    tags: ["Activity Recognition", "Domain Adaptation", "Wearables"],
    keywords: ["human activity recognition", "domain adaptation", "accelerometer data", "domain-agnostic", "wearable computing", "data heterogeneity", "leave-datasets-out", "generalization"],
    methodology: "Introduced leave-datasets-out evaluation regime for testing domain-agnostic performance. Compared state-of-the-art deep models against simple models with appropriate inductive bias using binary classification benchmark. Evaluated performance across multiple unseen domains arising from device, user, and environmental heterogeneity.",
    keyFindings: [
      "State-of-the-art deep models significantly under-perform in unseen domains compared to seen domains",
      "Simple model with appropriate inductive bias performs at least as well as deep models (p-values: 5.75x10−4 and 0.13)",
      "Simple models are at least 10 times faster to train than complex deep learning approaches",
      "Domain diversity under certain conditions improves performance on both seen and unseen domains",
      "Leave-datasets-out evaluation regime reveals limitations of current HAR approaches"
    ],
    relatedWork: "Builds on human activity recognition research and domain adaptation techniques. Addresses limitations of current approaches that require target domain data and proposes new evaluation methodologies for real-world deployment scenarios.",
    futureWork: "Further development of domain-agnostic HAR models suitable for real-world deployment, exploration of inductive biases that improve generalization, and extension of evaluation frameworks to multiclass classification problems.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{hasthanasombat2022investigating,
  title={Investigating domain-agnostic performance in activity recognition using accelerometer data},
  author={Hasthanasombat, Apinan and Ghosh, Abhirup and Spathis, Dimitris and Mascolo, Cecilia},
  booktitle={Adjunct Proceedings of the 2022 ACM International Joint Conference on Pervasive and Ubiquitous Computing and the 2022 ACM International Symposium on Wearable Computers},
  pages={329--334},
  year={2022}
}`
  },
  {
    id: "p11",
    title: "Publishing asynchronous event times with pufferfish privacy",
    authors: ["Jiaxin Ding", "Abhirup Ghosh", "Rik Sarkar", "Jie Gao"],
    venue: "DCOSS",
    year: 2022,
    abstract: "Addresses privacy concerns in publishing IoT event timestamps by formulating three privacy issues and proposing mechanisms using Pufferfish privacy framework with timestamp perturbation and fake event injection.",
    fullAbstract: "Publishing data from IoT devices raises concerns of leaking sensitive information. In this paper we consider the scenario of publishing data on events with timestamps. We formulate three privacy issues, namely, whether one can tell if an event happened or not; whether one can nail down the timestamp of an event within a given time interval; and whether one can infer the relative order of any two nearby events. We show that perturbation of event timestamps or adding fake events following carefully chosen distributions can address these privacy concerns. We present a rigorous study of privately publishing discrete event timestamps with privacy guarantees under the Pufferfish privacy framework. We also conduct extensive experiments to evaluate utility of the modified time series with real world location check-in and app usage data. Our mechanisms preserve the statistical utility of event data which are suitable for aggregate queries.",
    link: "https://ieeexplore.ieee.org/document/9884862",
    pdfLink: "",
    tags: ["Privacy", "IoT", "Differential Privacy"],
    keywords: ["pufferfish privacy", "event timestamps", "IoT privacy", "differential privacy", "time series", "location privacy", "fake events", "timestamp perturbation"],
    methodology: "Formulated three distinct privacy issues for event timestamp publishing: event occurrence detection, timestamp precision, and event ordering inference. Developed mechanisms using timestamp perturbation and fake event injection under Pufferfish privacy framework. Evaluated utility preservation using real-world location check-in and app usage datasets.",
    keyFindings: [
      "Identified three critical privacy vulnerabilities in publishing event timestamps from IoT devices",
      "Timestamp perturbation and fake event injection can effectively address privacy concerns",
      "Pufferfish privacy framework provides rigorous guarantees for discrete event timestamp publishing",
      "Proposed mechanisms preserve statistical utility suitable for aggregate queries",
      "Real-world evaluation on location check-in and app usage data demonstrates practical applicability"
    ],
    relatedWork: "Builds on differential privacy and Pufferfish privacy frameworks, extending them to the specific challenge of event timestamp publishing in IoT contexts. Related to location privacy, temporal privacy, and privacy-preserving data publishing research.",
    futureWork: "Extension to continuous event streams, integration with other privacy-preserving mechanisms, and application to additional IoT data types beyond timestamps.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{ding2022publishing,
  title={Publishing asynchronous event times with pufferfish privacy},
  author={Ding, Jiaxin and Ghosh, Abhirup and Sarkar, Rik and Gao, Jie},
  booktitle={2022 18th International Conference on Distributed Computing in Sensor Systems (DCOSS)},
  pages={53--60},
  year={2022},
  organization={IEEE}
}`
  },
  {
    id: "p12",
    title: "Continual and Sliding Window Release for Private Empirical Risk Minimization",
    authors: ["Lauren Watson", "Abhirup Ghosh", "Benedek Rozemberczki", "Rik Sarkar"],
    venue: "arXiv preprint",
    year: 2022,
    abstract: "Develops regularized empirical risk minimization algorithms for continually releasing private machine learning models with bounded differential privacy cost and near-optimal accuracy over infinite time horizons.",
    fullAbstract: "It is difficult to continually update private machine learning models with new data while maintaining privacy. Data incur increasing privacy loss – as measured by differential privacy – when they are used in repeated computations. In this paper, we describe regularized empirical risk minimization algorithms that continually release models for a recent window of data. One version of the algorithm uses the entire data history to improve the model for the recent window. The second version uses a sliding window of constant size to improve the model, ensuring more relevant models in case of evolving data. The algorithms operate in the framework of stochastic gradient descent. We prove that even with releasing a model at each time-step over an infinite time horizon, the privacy cost of any data point is bounded by a constant ε differential privacy, and the accuracy of the output models are close to optimal. Experiments on MNIST and Arxiv publications data show results consistent with the theory.",
    link: "https://arxiv.org/abs/2203.03594",
    pdfLink: "",
    tags: ["Differential Privacy", "Continual Learning", "Machine Learning"],
    keywords: ["differential privacy", "continual learning", "empirical risk minimization", "sliding window", "stochastic gradient descent", "privacy-preserving machine learning", "infinite time horizon", "regularization"],
    methodology: "Developed two regularized empirical risk minimization algorithms within stochastic gradient descent framework: one using entire data history and another using sliding window of constant size. Provided theoretical analysis proving bounded privacy cost and near-optimal accuracy. Evaluated on MNIST and Arxiv publications datasets.",
    keyFindings: [
      "Privacy cost of any data point bounded by constant ε differential privacy over infinite time horizon",
      "Accuracy of output models remains close to optimal despite privacy constraints",
      "Sliding window approach ensures more relevant models for evolving data distributions",
      "Theoretical guarantees consistent with experimental results on real datasets",
      "Successfully addresses the challenge of increasing privacy loss in repeated computations"
    ],
    relatedWork: "Builds on differential privacy theory and continual learning frameworks. Addresses the fundamental challenge of privacy accumulation in iterative machine learning algorithms, extending traditional differential privacy to dynamic settings with continuous model updates.",
    futureWork: "Extension to more complex model architectures, adaptive window sizing strategies, and application to federated learning scenarios with continual updates.",
    citations: 0,
    doi: "",
    bibtex: `@article{watson2022continual,
  title={Continual and Sliding Window Release for Private Empirical Risk Minimization},
  author={Watson, Lauren and Ghosh, Abhirup and Rozemberczki, Benedek and Sarkar, Rik},
  journal={arXiv preprint arXiv:2203.03594},
  year={2022}
}`
  },
  {
    id: "p13",
    title: "Benchmarking Federated Machine Unlearning methods for Tabular Data",
    authors: ["Chenguang Xiao", "Abhirup Ghosh", "Han Wu", "Shuo Wang", "Diederick van Thiel"],
    venue: "arXiv preprint",
    year: 2025,
    abstract: "Presents the first comprehensive benchmark study of machine unlearning methods in federated learning environments for tabular data, comparing fidelity, certifiability, and computational efficiency across various algorithms.",
    fullAbstract: "Machine unlearning, which enables a model to forget specific data upon request, is increasingly relevant in the era of privacy-centric machine learning, particularly within federated learning (FL) environments. This paper presents a pioneering study on benchmarking machine unlearning methods within a federated setting for tabular data, addressing the unique challenges posed by cross-silo FL where data privacy and communication efficiency are paramount. We explore unlearning at the feature and instance levels, employing both machine learning, random forest and logistic regression models. Our methodology benchmarks various unlearning algorithms, including fine-tuning and gradient-based approaches, across multiple datasets, with metrics focused on fidelity, certifiability, and computational efficiency. Experiments demonstrate that while fidelity remains high across methods, tree-based models excel in certifiability, ensuring exact unlearning, whereas gradient-based methods show improved computational efficiency. This study provides critical insights into the design and selection of unlearning algorithms tailored to the FL environment, offering a foundation for further research in privacy-preserving machine learning.",
    link: "https://arxiv.org/abs/2504.00921",
    pdfLink: "",
    tags: ["Federated Learning", "Machine Unlearning", "Privacy"],
    keywords: ["machine unlearning", "federated learning", "tabular data", "cross-silo FL", "privacy-preserving", "benchmarking", "fidelity", "certifiability", "computational efficiency"],
    methodology: "Comprehensive benchmarking study comparing machine unlearning methods in federated settings for tabular data. Evaluated feature and instance-level unlearning using random forest and logistic regression models. Tested fine-tuning and gradient-based approaches across multiple datasets with metrics measuring fidelity, certifiability, and computational efficiency.",
    keyFindings: [
      "First comprehensive benchmark of machine unlearning methods in federated learning environments",
      "High fidelity maintained across different unlearning methods in FL settings",
      "Tree-based models (random forest) excel in certifiability, ensuring exact unlearning",
      "Gradient-based methods demonstrate superior computational efficiency",
      "Cross-silo FL presents unique challenges for data privacy and communication efficiency in unlearning"
    ],
    relatedWork: "Builds on machine unlearning theory and federated learning frameworks. Addresses the intersection of privacy-preserving machine learning and the right to be forgotten in distributed settings, extending traditional unlearning methods to federated environments.",
    futureWork: "Extension to deep learning models in federated settings, development of more efficient unlearning algorithms for cross-device FL, and investigation of unlearning in heterogeneous federated environments.",
    citations: 0,
    doi: "",
    bibtex: `@article{xiao2025benchmarking,
  title={Benchmarking Federated Machine Unlearning methods for Tabular Data},
  author={Xiao, Chenguang and Ghosh, Abhirup and Wu, Han and Wang, Shuo and van Thiel, Diederick},
  journal={arXiv preprint arXiv:2504.00921},
  year={2025}
}`
  },
  {
    id: "p14",
    title: "Mobility-based individual poi recommendation to control the covid-19 spread",
    authors: ["Abhirup Ghosh", "Tong Xia"],
    venue: "IEEE Big Data",
    year: 2021,
    abstract: "Proposes an individual-level POI recommendation system that reduces COVID-19 infections by up to 50% while satisfying all check-in needs, based on crowd density and temporal visit patterns.",
    fullAbstract: "Societal functions have stalled during COVID-19 to reduce its spread in the population. It has been shown that visits to different venues have a large effect on spreading the virus. Hence, population-level mobility interventions like reopening selective category of venues have been proposed, for example, opening schools and offices but preventing people from visiting restaurants. These measures, although help to mitigate infection, still fail to satisfy people's needs and hope of going back to normality. In this context, here we propose an individual level POI recommendation system that can recommend venues to users according to their preference and at the same time, can lead to as few infections as possible. The key idea behind the system is that the risk of getting infected grows with the number of unique customers that had visited the venue previously, and it is safer to visit a less crowded place during a specific time slot. We evaluate the proposed system using both theory and real check-in datasets from three cities. Based on simulation on real-world data, we present a surprising result: it is possible to recommend POIs in such a way that the total infected population reduces by up to 50% compared to that following original check-ins. This result is comparable to that when 50% of the visits are blocked, yet our method allows all check-in needs.",
    link: "https://ieeexplore.ieee.org/document/9671717",
    pdfLink: "",
    tags: ["COVID-19", "Mobility", "Recommendation Systems"],
    keywords: ["COVID-19", "point of interest", "mobility", "recommendation systems", "infection control", "crowd density", "temporal patterns", "epidemiological modeling"],
    methodology: "Developed individual-level POI recommendation system based on infection risk modeling. Used crowd density and temporal visit patterns to assess venue safety. Evaluated using theoretical analysis and real check-in datasets from three cities. Compared infection outcomes against original check-in patterns and visit blocking strategies.",
    keyFindings: [
      "Individual POI recommendations can reduce total infected population by up to 50%",
      "Performance comparable to blocking 50% of visits while satisfying all check-in needs",
      "Infection risk correlates with number of unique previous customers at venues",
      "Temporal slot selection significantly impacts infection probability",
      "Real-world simulation across three cities validates theoretical predictions"
    ],
    relatedWork: "Builds on epidemiological modeling of COVID-19 transmission and mobility-based intervention strategies. Related to location-based services and recommendation systems research, extending them to public health applications during pandemic conditions.",
    futureWork: "Extension to other infectious diseases, integration with real-time mobility data, and development of privacy-preserving recommendation mechanisms for health-sensitive applications.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{ghosh2021mobility,
  title={Mobility-based individual poi recommendation to control the covid-19 spread},
  author={Ghosh, Abhirup and Xia, Tong},
  booktitle={2021 IEEE International Conference on Big Data (Big Data)},
  pages={4356--4364},
  year={2021},
  organization={IEEE}
}`
  },
  {
    id: "p15",
    title: "HYPO: skew-resilient partitioning for trajectory datasets",
    authors: ["Giannis Evagorou", "Abhirup Ghosh", "Thomas Heinis"],
    venue: "ACM SIGSPATIAL Workshop",
    year: 2021,
    abstract: "Develops HYPO, a hybrid partitioning algorithm for distributing trajectory datasets across clusters that performs robustly against data skew, enabling efficient Query by Path execution at scale.",
    fullAbstract: "The rapid increase of GPS-enabled devices has led to immense amounts of trajectory data being collected and analyzed. To provide insight into these datasets, a number of spatio-temporal queries need to be executed efficiently and at scale. One such important query is the Query by Path, which given a series of road segments and a time interval, retrieves all trajectories that have passed through the road segments within a given time interval. The Query by Path finds application in many areas, including traffic management, transportation planning and fleet monitoring. In this paper we develop an approach to partition and distribute trajectories across a cluster and execute queries by path at scale. At the center of our approach is the partitioning of the entire dataset and indexing each partition with a Trie. We develop a basic set of partitioning approaches and show that each can be rendered inefficient by skew in the dataset. We consequently propose a HYbrid PartitiOning algorithm (HYPO) that performs robustly in face of skew. We also provide the cost models to configure HYPO. Finally we assess its performance extensively using both real and synthetic datasets to demonstrate that it scales well in face of skew.",
    link: "https://dl.acm.org/doi/10.1145/3486635.3491076",
    pdfLink: "",
    tags: ["Trajectory Data", "Distributed Systems", "Spatial Computing"],
    keywords: ["trajectory data", "data partitioning", "distributed systems", "spatial databases", "query by path", "data skew", "trie indexing", "GPS data"],
    methodology: "Developed hybrid partitioning algorithm (HYPO) for trajectory datasets distributed across clusters. Implemented Trie-based indexing for each partition. Created cost models for algorithm configuration. Evaluated performance using both real and synthetic datasets with focus on skew resilience and scalability.",
    keyFindings: [
      "Basic partitioning approaches become inefficient when faced with dataset skew",
      "HYPO algorithm performs robustly against various types of data skew",
      "Trie-based indexing enables efficient Query by Path execution at scale",
      "Cost models provide effective configuration guidance for HYPO deployment",
      "Extensive evaluation demonstrates superior scalability compared to baseline approaches"
    ],
    relatedWork: "Builds on spatial database systems and distributed computing research. Addresses specific challenges of trajectory data management in big data environments, extending traditional spatial partitioning techniques to handle GPS trajectory datasets with temporal components.",
    futureWork: "Extension to other spatio-temporal query types, adaptive partitioning strategies that respond to changing data distributions, and integration with real-time trajectory processing systems.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{evagorou2021hypo,
  title={HYPO: skew-resilient partitioning for trajectory datasets},
  author={Evagorou, Giannis and Ghosh, Abhirup and Heinis, Thomas},
  booktitle={Proceedings of the 5th ACM SIGSPATIAL International Workshop on Location-based Recommendations, Geosocial Networks and Geoadvertising},
  pages={1--10},
  year={2021}
}`
  },
  {
    id: "p16",
    title: "Heterogeneous interventions reduce the spread of COVID-19 in simulations on real mobility data",
    authors: ["Haotian Wang", "Abhirup Ghosh", "Jiaxin Ding", "Rik Sarkar", "Jie Gao"],
    venue: "Scientific Reports",
    year: 2021,
    abstract: "Demonstrates that targeted interventions focused on highly mobile individuals and popular venues are more effective than broad lockdowns, reducing peak infection rates while maintaining high social activity levels.",
    fullAbstract: "Major interventions have been introduced worldwide to slow down the spread of the SARS-CoV-2 virus. Large scale lockdown of human movements are effective in reducing the spread, but they come at a cost of significantly limited societal functions. We show that natural human movements are statistically diverse, and the spread of the disease is significantly influenced by a small group of active individuals and gathering venues. We find that interventions focused on these most mobile individuals and popular venues reduce both the peak infection rate and the total infected population while retaining high social activity levels. These trends are seen consistently in simulations with real human mobility data of different scales, resolutions, and modalities from multiple cities across the world. The observation implies that compared to broad sweeping interventions, more heterogeneous strategies that are targeted based on the network effects in human mobility provide a better balance between pandemic control and regular social activities.",
    link: "https://doi.org/10.1038/s41598-021-87034-z",
    pdfLink: "",
    tags: ["COVID-19", "Mobility", "Epidemiological Modeling"],
    keywords: ["COVID-19", "heterogeneous interventions", "mobility data", "epidemiological modeling", "network effects", "pandemic control", "social activities", "targeted interventions"],
    methodology: "Analyzed real human mobility data from multiple cities worldwide across different scales, resolutions, and modalities. Developed epidemiological simulations incorporating network effects in human mobility. Compared broad lockdown strategies with targeted interventions focusing on highly mobile individuals and popular venues.",
    keyFindings: [
      "Small group of active individuals and gathering venues significantly influence disease spread",
      "Targeted interventions reduce both peak infection rate and total infected population",
      "Heterogeneous strategies maintain high social activity levels compared to broad lockdowns",
      "Trends consistent across multiple cities with different mobility data characteristics",
      "Network effects in human mobility provide better balance between pandemic control and social activities"
    ],
    relatedWork: "Builds on epidemiological modeling of COVID-19 transmission and mobility-based intervention research. Extends traditional disease spread models by incorporating detailed human mobility patterns and network effects in real-world scenarios.",
    futureWork: "Application to other infectious diseases, development of real-time intervention recommendation systems, and integration with privacy-preserving mobility tracking technologies.",
    citations: 0,
    doi: "10.1038/s41598-021-87034-z",
    bibtex: `@article{wang2021heterogeneous,
  title={Heterogeneous interventions reduce the spread of COVID-19 in simulations on real mobility data},
  author={Wang, Haotian and Ghosh, Abhirup and Ding, Jiaxin and Sarkar, Rik and Gao, Jie},
  journal={Scientific reports},
  volume={11},
  number={1},
  pages={7809},
  year={2021},
  publisher={Nature Publishing Group UK London}
}`
  },
  {
    id: "p17",
    title: "Differentially private range counting in planar graphs for spatial sensing",
    authors: ["Abhirup Ghosh", "Jiaxin Ding", "Rik Sarkar", "Jie Gao"],
    venue: "IEEE INFOCOM",
    year: 2020,
    abstract: "Develops novel hierarchical data structures for differentially private range counting over arbitrary planar graphs, enabling efficient spatial sensing queries with poly-logarithmic error and distributed processing capabilities.",
    fullAbstract: "This paper considers the problem of privately reporting counts of events recorded by devices in different regions of the plane. Unlike previous range query methods, our approach is not limited to rectangular ranges. We devise novel hierarchical data structures to answer queries over arbitrary planar graphs. This construction relies on balanced planar separators to represent shortest paths using O(log n) number of canonical paths, where n is the number of nodes in the graph. Pre-computed sums along these canonical paths allow efficient computations of 1D-counting range queries along any shortest path. We make use of differential forms together with the 1D mechanism to answer 2D queries in which a range is a union of faces in the planar graph. The methods are designed such that the range queries could be answered with differential privacy guarantee on any single event, with only a poly-logarithmic error. They also allow private range queries to be performed in a distributed setup. Theoretical and experimental results confirm that the methods are efficient and accurate on real data and incur less error than competing existing methods.",
    link: "https://ieeexplore.ieee.org/document/9155375",
    pdfLink: "",
    tags: ["Differential Privacy", "Spatial Computing", "Graph Algorithms"],
    keywords: ["differential privacy", "planar graphs", "range counting", "spatial sensing", "hierarchical data structures", "balanced separators", "canonical paths", "distributed privacy"],
    methodology: "Developed hierarchical data structures using balanced planar separators for arbitrary planar graph queries. Constructed canonical path representations with O(log n) complexity for shortest path queries. Combined differential forms with 1D mechanisms for 2D range queries. Evaluated theoretical complexity and experimental accuracy on real datasets.",
    keyFindings: [
      "Novel approach extends beyond rectangular ranges to arbitrary planar graph regions",
      "Balanced planar separators enable O(log n) canonical path representation for shortest paths",
      "Differential forms combined with 1D mechanisms provide efficient 2D query processing",
      "Differential privacy guarantees maintained with only poly-logarithmic error",
      "Distributed setup support enables scalable private spatial sensing applications"
    ],
    relatedWork: "Builds on differential privacy theory and computational geometry research. Extends traditional range query methods to non-rectangular regions using planar graph structures, combining privacy-preserving mechanisms with efficient spatial data structures.",
    futureWork: "Extension to higher-dimensional spaces, adaptive privacy budget allocation for dynamic spatial queries, and integration with real-time spatial sensing systems.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{ghosh2020differentially,
  title={Differentially private range counting in planar graphs for spatial sensing},
  author={Ghosh, Abhirup and Ding, Jiaxin and Sarkar, Rik and Gao, Jie},
  booktitle={IEEE INFOCOM 2020-IEEE Conference on Computer Communications},
  pages={2233--2242},
  year={2020},
  organization={IEEE}
}`
  },
  {
    id: "p18",
    title: "Machine learning and privacy preserving algorithms for spatial and temporal sensing",
    authors: ["Abhirup Ghosh"],
    venue: "PhD Thesis, University of Edinburgh",
    year: 2019,
    abstract: "PhD thesis proposing theoretically grounded algorithms for learning from location and time stamps in sensor data, leveraging geometry, topology, and statistics for privacy-preserving spatial-temporal analysis.",
    fullAbstract: "Sensing physical and social environments are ubiquitous in modern mobile phones, IoT devices, and infrastructure-based settings. Information engraved in such data, especially the time and location attributes have unprecedented potential to characterize individual and crowd behaviour, natural and technological processes. However, it is challenging to extract abstract knowledge from the data due to its massive size, sequential structure, asynchronous operation, noisy characteristics, privacy concerns, and real time analysis requirements. Therefore, the primary goal of this thesis is to propose theoretically grounded and practically useful algorithms to learn from location and time stamps in sensor data. The proposed methods are inspired by tools from geometry, topology, and statistics. They leverage structures in the temporal and spatial data by probabilistically modeling noise, exploring topological structures embedded, and utilizing statistical structure to protect personal information and simultaneously learn aggregate information. Proposed algorithms are geared towards streaming and distributed operation for efficiency. The usefulness of the methods is argued using mathematical analysis and empirical experiments on real and artificial datasets.",
    link: "https://era.ed.ac.uk/handle/1842/36923",
    pdfLink: "",
    tags: ["PhD Thesis", "Spatial-Temporal", "Privacy", "Machine Learning"],
    keywords: ["spatial-temporal sensing", "privacy-preserving algorithms", "machine learning", "geometry", "topology", "statistics", "streaming algorithms", "distributed computing"],
    methodology: "Developed theoretically grounded algorithms combining geometry, topology, and statistics for spatial-temporal data analysis. Focused on probabilistic noise modeling, topological structure exploration, and statistical privacy protection. Designed algorithms for streaming and distributed operation with emphasis on real-time analysis capabilities.",
    keyFindings: [
      "Novel integration of geometry, topology, and statistics for spatial-temporal sensing",
      "Probabilistic noise modeling enables robust knowledge extraction from sensor data",
      "Topological structures in spatial-temporal data provide valuable analytical insights",
      "Statistical privacy protection can be achieved while learning aggregate information",
      "Streaming and distributed algorithms enable real-time analysis of large-scale sensor data"
    ],
    relatedWork: "Foundational work combining computational geometry, algebraic topology, and statistical machine learning for sensor data analysis. Bridges theoretical computer science with practical applications in mobile sensing and IoT data processing.",
    futureWork: "This thesis laid the foundation for subsequent work in federated learning, differential privacy applications, and mobile health sensing that continues in current research directions.",
    citations: 0,
    doi: "",
    bibtex: `@article{ghosh2019machine,
  title={Machine learning and privacy preserving algorithms for spatial and temporal sensing},
  author={Ghosh, Abhirup},
  year={2019},
  publisher={The University of Edinburgh}
}`
  },
  {
    id: "p19",
    title: "Topological signatures for fast mobility analysis",
    authors: ["Abhirup Ghosh", "Benedek Rozemberczki", "Subramanian Ramamoorthy", "Rik Sarkar"],
    venue: "ACM SIGSPATIAL",
    year: 2018,
    abstract: "Introduces topological signatures that map trajectories to low-dimensional Euclidean space for efficient mobility analysis, enabling faster data mining tasks and accurate mobility prediction with theoretical guarantees.",
    fullAbstract: "Analytic methods can be difficult to build and costly to train for mobility data. We show that information about the topology of the space and how mobile objects navigate the obstacles can be used to extract insights about mobility at larger distance scales. The main contribution of this paper is a topological signature that maps each trajectory to a relatively low dimensional Euclidean space, so that now they are amenable to standard analytic techniques. Data mining tasks: nearest neighbor search with locality sensitive hashing, clustering, regression, etc., work more efficiently in this signature space. We define the problem of mobility prediction at different distance scales, and show that with the signatures simple k nearest neighbor based regression perform accurate prediction. Experiments on multiple real datasets show that the framework using topological signatures is accurate on all tasks, and substantially more efficient than machine learning applied to raw data. Theoretical results show that the signatures contain enough topological information to reconstruct non-self-intersecting trajectories up to homotopy type. The construction of signatures is based on a differential form that can be generated in a distributed setting using local communication, and a signature can be locally and inexpensively updated and communicated by a mobile agent.",
    link: "https://dl.acm.org/doi/10.1145/3274895.3274943",
    pdfLink: "",
    tags: ["Topology", "Mobility", "Trajectory Analysis"],
    keywords: ["topological signatures", "mobility analysis", "trajectory mapping", "differential forms", "homotopy type", "distributed computation", "k-nearest neighbor", "locality sensitive hashing"],
    methodology: "Developed topological signatures that map trajectories to low-dimensional Euclidean space using differential forms. Implemented distributed signature generation with local communication. Evaluated on multiple real datasets comparing efficiency against machine learning on raw data. Provided theoretical analysis of signature reconstruction capabilities.",
    keyFindings: [
      "Topological signatures enable efficient mapping of trajectories to low-dimensional Euclidean space",
      "Standard analytic techniques work more efficiently in signature space than on raw mobility data",
      "Simple k-nearest neighbor regression achieves accurate mobility prediction using signatures",
      "Framework substantially more efficient than machine learning applied to raw trajectory data",
      "Signatures contain sufficient topological information to reconstruct trajectories up to homotopy type"
    ],
    relatedWork: "Builds on algebraic topology and differential geometry for trajectory analysis. Extends traditional mobility analysis by incorporating topological invariants, connecting computational topology with practical mobility prediction and data mining applications.",
    futureWork: "Extension to higher-dimensional mobility spaces, integration with privacy-preserving mechanisms, and application to real-time trajectory prediction systems.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{ghosh2018topological,
  title={Topological signatures for fast mobility analysis},
  author={Ghosh, Abhirup and Rozemberczki, Benedek and Ramamoorthy, Subramanian and Sarkar, Rik},
  booktitle={Proceedings of the 26th ACM SIGSPATIAL International Conference on Advances in Geographic Information Systems},
  pages={159--168},
  year={2018}
}`
  },
  {
    id: "p20",
    title: "Finding periodic discrete events in noisy streams",
    authors: ["Abhirup Ghosh", "Christopher Lucas", "Rik Sarkar"],
    venue: "ACM CIKM",
    year: 2017,
    abstract: "Develops a particle filter-based model for detecting and predicting periodic events in noisy streams with constant computational complexity, enabling real-time performance in low-resource settings.",
    fullAbstract: "Periodic phenomena are ubiquitous, but detecting and predicting periodic events can be difficult in noisy environments. We describe a model of periodic events that covers both idealized and realistic scenarios characterized by multiple kinds of noise. The model incorporates false-positive events and the possibility that the underlying period and phase of the events change over time. We then describe a particle filter that can efficiently and accurately estimate the parameters of the process generating periodic events intermingled with independent noise events. The system has a small memory footprint, and, unlike alternative methods, its computational complexity is constant in the number of events that have been observed. As a result, it can be applied in low-resource settings that require real-time performance over long periods of time. In experiments on real and simulated data we find that it outperforms existing methods in accuracy and can track changes in periodicity and other characteristics in dynamic event streams.",
    link: "https://dl.acm.org/doi/10.1145/3132847.3132953",
    pdfLink: "",
    tags: ["Time Series", "Streaming Algorithms", "Periodic Detection"],
    keywords: ["periodic events", "particle filter", "noisy streams", "time series analysis", "streaming algorithms", "real-time processing", "low-resource computing", "dynamic event streams"],
    methodology: "Developed a probabilistic model for periodic events incorporating false-positive events and time-varying parameters. Implemented particle filter for parameter estimation with constant computational complexity. Evaluated on both real and simulated datasets comparing accuracy and computational efficiency against existing methods.",
    keyFindings: [
      "Particle filter achieves constant computational complexity independent of observed events",
      "Model successfully handles false-positive events and time-varying periodicity",
      "System maintains small memory footprint suitable for low-resource environments",
      "Outperforms existing methods in accuracy on both real and simulated data",
      "Can track changes in periodicity and phase in dynamic event streams"
    ],
    relatedWork: "Builds on time series analysis and sequential Monte Carlo methods. Extends traditional periodic detection by incorporating realistic noise models and providing computational guarantees for streaming applications.",
    futureWork: "Extension to multi-periodic signals, integration with distributed streaming systems, and application to IoT sensor networks with intermittent connectivity.",
    citations: 0,
    doi: "",
    bibtex: `@inproceedings{ghosh2017finding,
  title={Finding periodic discrete events in noisy streams},
  author={Ghosh, Abhirup and Lucas, Christopher and Sarkar, Rik},
  booktitle={Proceedings of the 2017 ACM on Conference on Information and Knowledge Management},
  pages={627--636},
  year={2017}
}`
  },
  {
    id: "p21",
    title: "In-Network Approximate and Efficient Spatiotemporal Range Queries on Moving Objects",
    authors: ["Guang Yang", "Abhirup Ghosh", "Liang Liang", "Thomas Heinis"],
    venue: "EDBT",
    year: 2024,
    abstract: "Proposes a novel planar graph-based framework for privacy-aware in-network spatiotemporal range queries, achieving 13.8% relative error with 25.6% of sensors and 3.5× speedup over exact methods.",
    fullAbstract: "Data aggregations enable privacy-aware data analytics for moving objects. A spatiotemporal range count query is a fundamental query that aggregates the count of objects in a given spatial region and a time interval. Existing works are designed for centralized systems, which lead to issues with extensive communication and the potential for data leaks. Current in-network systems suffer from the distinct count problem (counting the same objects multiple times) and the dead space problem (excessive intra-communication from ill-suited spatial subdivisions). We propose a novel framework based on a planar graph representation for efficient privacy-aware in-network aggregate queries. Unlike conventional spatial decomposition methods, our framework uses sensor placement techniques to select sensors to reduce dead space. A submodular maximization-based method is introduced when the query distribution is known and a host of sampling methods are used when the query distribution is unknown or dynamic. We avoid double counting by tracking movements along the graph edges using discrete differential forms. We support queries with arbitrary temporal intervals with a constant-sized regression model that accelerates the query performance and reduces the storage size. We evaluate our method on real-world mobility data, which yields us a relative error of at most 13.8% with 25.6% of sensors while achieving a speedup of 3.5×, 69.81% reduction in sensors accessed, and a storage reduction of 99.96% compared to finding the exact count.",
    link: "https://www.semanticscholar.org/paper/In-Network-Approximate-and-Efficient-Spatiotemporal-Yang-Liang/de0d44dbd81b87c1caf9dfb7474a3049f9a8c02c",
    pdfLink: "",
    tags: ["Spatial Computing", "In-Network Processing", "Moving Objects"],
    keywords: ["in-network processing", "spatiotemporal queries", "moving objects", "planar graphs", "discrete differential forms", "submodular optimization", "privacy-aware analytics", "sensor networks"],
    methodology: "Developed planar graph-based framework for in-network spatiotemporal range queries. Used sensor placement techniques and submodular maximization for optimal sensor selection. Applied discrete differential forms to track object movements and avoid double counting. Implemented constant-sized regression models for temporal query support.",
    keyFindings: [
      "Achieves 13.8% relative error using only 25.6% of available sensors",
      "Provides 3.5× speedup compared to exact count methods",
      "Reduces sensors accessed by 69.81% compared to baseline approaches",
      "Achieves 99.96% storage reduction through efficient data structures",
      "Successfully addresses both distinct count and dead space problems in in-network systems"
    ],
    relatedWork: "Builds on in-network processing, spatiotemporal databases, and sensor network research. Extends traditional centralized spatiotemporal query processing to distributed in-network settings with privacy preservation and efficiency guarantees.",
    futureWork: "Extension to more complex spatiotemporal queries, adaptive sensor selection strategies, and integration with real-time streaming analytics systems.",
    citations: 0,
    doi: "",
    bibtex: `@article{yang2024network,
  title={In-Network Approximate and Efficient Spatiotemporal Range Queries on Moving Objects},
  author={Yang, Guang and Ghosh, Abhirup and Liang, Liang and Heinis, Thomas},
  journal={International Conference on Extending Database Technology (EDBT)},
  year={2024}
}`
  }
  // Add more papers as needed...
];